// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// unif_mt_cpp
Rcpp::NumericVector unif_mt_cpp(unsigned int seed, unsigned int n);
RcppExport SEXP _Random_unif_mt_cpp(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(unif_mt_cpp(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// unif_mt_cpp_parallel
Rcpp::NumericVector unif_mt_cpp_parallel(Rcpp::IntegerVector seeds, unsigned int n, unsigned int n_cores);
RcppExport SEXP _Random_unif_mt_cpp_parallel(SEXP seedsSEXP, SEXP nSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(unif_mt_cpp_parallel(seeds, n, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// unif_mt_c
Rcpp::NumericVector unif_mt_c(unsigned int seed, unsigned int n);
RcppExport SEXP _Random_unif_mt_c(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(unif_mt_c(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// unif_wh_cpp
Rcpp::NumericVector unif_wh_cpp(unsigned int seed, unsigned int n);
RcppExport SEXP _Random_unif_wh_cpp(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(unif_wh_cpp(seed, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Random_unif_mt_cpp", (DL_FUNC) &_Random_unif_mt_cpp, 2},
    {"_Random_unif_mt_cpp_parallel", (DL_FUNC) &_Random_unif_mt_cpp_parallel, 3},
    {"_Random_unif_mt_c", (DL_FUNC) &_Random_unif_mt_c, 2},
    {"_Random_unif_wh_cpp", (DL_FUNC) &_Random_unif_wh_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Random(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
