# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MT_CPP <- function(seed, n, n_cores) {
    .Call(`_Random_MT_CPP`, seed, n, n_cores)
}

MT <- function(seed, n) {
    .Call(`_Random_MT`, seed, n)
}

