# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unif_mt_cpp <- function(seed, n) {
    .Call(`_Random_unif_mt_cpp`, seed, n)
}

unif_mt_cpp_parallel <- function(seeds, n, n_cores) {
    .Call(`_Random_unif_mt_cpp_parallel`, seeds, n, n_cores)
}

unif_mt_c <- function(seed, n) {
    .Call(`_Random_unif_mt_c`, seed, n)
}

